.TH _PRINTF 1 _printf\-1.0
.SH NAME
_printf \- Format and print data
.SH SYNOPSIS
_printf(const char *format, ...);
_printf FORMAT [ARGUMENT...]
.SH DESCRIPTION
.B _printf
is a function that formats text and writes it to standard output. The 
.B arguments
 are formatted under control of the 
.B format 
operand.
.SH OPTION 
.B [%d] or [%i]
to print integer in base 10.
.B [%s]
to print a string.
.B [%c]
to print a single character
.B [%%]
to print a % character alone.
.SH EXEMPLES
.RB _printf("Ma name is %s", "James Bond");
. Output = James Bond
.AUHTORS
Cyrien Gehu, Théo Lesmayoux and Adrien Vieilledent
.SH COPYRIGHT
Copyright © 2024  HOLBIE ONE, Inc.   License  GNU-HOLBERTON    Version 1  <https://www.holbertonschool.com>.
